### ISSUE TITLE
Not usable with composer

### ISSUE THREAD

**Issue by staelche** [blackfireio/player#30]
The alpha 3 seems not to be usable with composer, anymore.

The path in the blackfire-player.php in /bin to the autoload.php of composer is not correct and the link to the bin php file in /vendor/bin/ is missing.

Would be great if the player is still usable as a dependency loaded by composer in the future :-)

**Comment by romainneutron** [comment]
Hello,

As mentioned in the [changelog](https://github.com/blackfireio/player/blob/master/CHANGELOG#L6-L8), the blackfire player can only be used as a phar executable since version 0.5.0

**Comment by staelche** [comment]
And it does not make sense for you to support a usage via composer, as well, with a minimum of effort? 
I can't understand this decision.

**Comment by fabpot** [comment]
@staelche That's a tough decision we made when rewriting the new version. The reasoning goes like this: the new version provides a DSL that enables anyone to write HTTP browsing scenarii. We didn't want two ways of doing the same thing. We also want to support more than Guzzle for HTTP requests (think Selenium for instance or any headless browser). We also envision a next version that could be using Go instead of PHP (to ease installation amongst other benefits). So, letting people using the player via Composer would give the false idea that the player is more a library than a CLI tool.

**Comment by staelche** [comment]
I understand. First, I felt the same way when I started installing packages which contains only tools and not libraries.

The thing is, why I find the composer way quite handy, I am sharing a CI environment with several teams at work and I don't want to rely on the tools like code sniffer, phpunit, etc. which are globally installed on the server. Most of the time they are not up to date or are installed in different versions I want to use. So I started to define those tools as dev dependency calling them directly during the job execution.

I talked to some other colleagues who told me about Phive and some other initiatives to be able to automate a phar installation which is maybe the new way to do something like this. I don't know what the future brings.

Probably I will go with a fork for now adding the missing parts and porting the new features from time to time. If you go with Go probably I start maintaining a package with the binary ;-). Currently I provide to many tools via composer which I need in the CI environment that it does not make sense to handle it differently for the player till a better way arises and I can switch completely.

Thank you for your in depth answer Fabien.
